// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data_access

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            uuid.UUID `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	CreatedAt     time.Time `json:"created_at"`
	// enum defined in code
	State    int16     `json:"state"`
	StatedAt time.Time `json:"stated_at"`
}

type UserCredential struct {
	UserID     uuid.UUID `json:"user_id"`
	Credential string    `json:"credential"`
	Salt       string    `json:"salt"`
}

type UserSocialToken struct {
	UserID uuid.UUID `json:"user_id"`
	// enum defined in code
	ProviderType string             `json:"provider_type"`
	AccessToken  pgtype.Text        `json:"access_token"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	Expires      pgtype.Timestamptz `json:"expires"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}
